"""Optional, lazy read-only client for the 4DAI MongoDB.

4DAI stores sample context, 2D image metadata, and optional moisture data in
MongoDB. This module lets the 3DAI API enrich its 3D scan data with the
matching 4DAI record for a shared ``sample_id`` (which is the 4DAI record
``_id`` generated by 4DAI's FastAPI server).

Design constraints (see docs/4dai_integration.md):

- 3DAI must start and serve all of its own endpoints even if ``pymongo`` is not
  installed or Mongo is unreachable. Nothing here is imported at module load of
  ``main.py`` in a way that can fail; the Mongo client is created lazily and all
  errors degrade to "not configured / not available" rather than raising.
- Read-only. No writes, no hardware, no camera/Kinect imports.

4DAI schema:
    db "Collections"
      <category>: _id == sample_id plus dynamic fields from
                  Server/settings/<category>.json
      images:     optional legacy/shared image metadata with sample_id,
                  image_path, etc.
"""

import os
from typing import Any, Optional


DEFAULT_DB_NAME = "Collections"
LEGACY_SAMPLE_COLLECTIONS = ("vegetable", "soil")
DEFAULT_IMAGE_COLLECTIONS = ("images",)
DEFAULT_NON_SAMPLE_COLLECTIONS = (
    "images",
    "image",
    "fs.files",
    "fs.chunks",
)

# Module-level cache so we build at most one MongoClient per process.
_client = None
_client_built = False


def is_configured() -> bool:
    """True if a 4DAI Mongo URL has been configured via the environment."""
    return bool(os.getenv("FOURDAI_MONGO_URL", "").strip())


def get_db_name() -> str:
    return os.getenv("FOURDAI_DB_NAME", "").strip() or DEFAULT_DB_NAME


def _csv_env(name: str) -> list[str]:
    raw = os.getenv(name, "")
    return [part.strip() for part in raw.split(",") if part.strip()]


def _configured_sample_collections() -> list[str]:
    return _csv_env("FOURDAI_CATEGORY_COLLECTIONS")


def _configured_image_collections() -> list[str]:
    return _csv_env("FOURDAI_IMAGE_COLLECTIONS") or list(DEFAULT_IMAGE_COLLECTIONS)


def _non_sample_collections() -> set[str]:
    return set(DEFAULT_NON_SAMPLE_COLLECTIONS) | set(_csv_env("FOURDAI_NON_SAMPLE_COLLECTIONS"))


def sample_collection_names(db) -> list[str]:
    """Return candidate 4DAI category collections to search for sample records.

    The current 4DAI contract stores each dynamic category in its own Mongo
    collection, with ``sample_id`` as the document ``_id``. If
    ``FOURDAI_CATEGORY_COLLECTIONS`` is set, it is authoritative. Otherwise we
    ask Mongo for its collection names and skip obvious non-sample collections.
    Test doubles and legacy deployments that cannot list collections fall back
    to the original ``vegetable`` / ``soil`` names.
    """
    configured = _configured_sample_collections()
    if configured:
        return configured

    try:
        names = list(db.list_collection_names())
    except Exception:
        return list(LEGACY_SAMPLE_COLLECTIONS)

    blocked = _non_sample_collections()
    candidates = []
    for name in names:
        lower = name.lower()
        if name in blocked or lower in blocked:
            continue
        if lower.startswith("system.") or lower.endswith(".files") or lower.endswith(".chunks"):
            continue
        candidates.append(name)

    return candidates or list(LEGACY_SAMPLE_COLLECTIONS)


def _get_client():
    """Build (once) and return a MongoClient, or None if unavailable.

    Returns None if 4DAI is not configured, if pymongo is not installed, or if
    the client cannot be constructed. Never raises.
    """
    global _client, _client_built
    if _client_built:
        return _client

    _client_built = True
    url = os.getenv("FOURDAI_MONGO_URL", "").strip()
    if not url:
        _client = None
        return _client

    try:
        from pymongo import MongoClient
    except ImportError:
        _client = None
        return _client

    try:
        # serverSelectionTimeoutMS keeps a down Mongo from hanging the request.
        timeout_ms = int(os.getenv("FOURDAI_MONGO_TIMEOUT_MS", "1500"))
        _client = MongoClient(url, serverSelectionTimeoutMS=timeout_ms)
    except Exception:
        _client = None
    return _client


def reset_client_cache() -> None:
    """Drop the cached client. Intended for tests that change the environment."""
    global _client, _client_built
    _client = None
    _client_built = False


def _shape_image_doc(doc: Any) -> dict[str, Any]:
    if not isinstance(doc, dict):
        return {"image_id": str(doc)}

    shaped = {}
    for key, value in doc.items():
        if key == "_id":
            shaped["image_id"] = str(value)
        else:
            shaped[key] = value
    return shaped


def shape_record(category: str, doc: dict[str, Any], images: list[Any]) -> dict[str, Any]:
    """Shape a raw 4DAI Mongo document into the API record form.

    Pure function: no I/O, so it is unit-testable without pymongo or a live
    Mongo. ``category`` is the Mongo collection/category name; ``doc`` is the
    raw Mongo doc; ``images`` are optional image metadata docs or legacy image
    id strings for the sample.

    4DAI's current dynamic-category documents are shaped
    ``{"_id", "date", "data": {<dynamic context fields>}}`` -- the per-sample
    context (moisture, common name, etc.) is nested under ``data``. We lift
    those fields to the top of ``record`` so callers can read
    ``record["Moisture"]`` directly, and expose ``record["_meta"]`` for the
    envelope fields (``date`` and anything else outside ``data``). Legacy flat
    ``vegetable`` / ``soil`` documents with no ``data`` key keep their fields at
    the top of ``record`` unchanged.
    """
    envelope = {k: v for k, v in doc.items() if k not in ("_id", "data")}
    data = doc.get("data")
    if isinstance(data, dict):
        # Dynamic-category shape: dynamic fields come from ``data``; ``date`` and
        # any other envelope keys are preserved under ``_meta`` for provenance.
        fields: dict[str, Any] = dict(data)
        if envelope:
            fields["_meta"] = envelope
    else:
        # Legacy flat shape (vegetable/soil) or a doc with no ``data`` object.
        fields = envelope

    shaped_images = [_shape_image_doc(image) for image in images]
    image_ids = [image["image_id"] for image in shaped_images if "image_id" in image]
    return {
        "kind": category,
        "category": category,
        "collection": category,
        "record": fields,
        "image_ids": image_ids,
        "images": shaped_images,
    }


def _fetch_images(sample_id: str, db) -> list[dict[str, Any]]:
    images: list[dict[str, Any]] = []
    for coll_name in _configured_image_collections():
        try:
            images.extend(db[coll_name].find({"sample_id": sample_id}))
        except Exception:
            continue
    return images


def fetch_sample(sample_id: str, db=None) -> Optional[dict[str, Any]]:
    """Return the 4DAI record for ``sample_id`` (its Mongo ``_id``), or None.

    Looks in dynamic 4DAI category collections. Resolves image metadata from
    the configured image collection(s), defaulting to the legacy ``images``
    collection. ``db`` may be injected for testing; otherwise the configured
    Mongo database is used.

    Never raises on connection or driver problems; returns None instead so the
    caller can degrade gracefully.
    """
    if db is None:
        client = _get_client()
        if client is None:
            return None
        try:
            db = client[get_db_name()]
        except Exception:
            return None

    for coll_name in sample_collection_names(db):
        try:
            doc = db[coll_name].find_one({"_id": sample_id})
        except Exception:
            continue

        if doc is not None:
            images = _fetch_images(sample_id, db)
            return shape_record(coll_name, doc, images)

    return None
